using System.Xml.Serialization;

namespace Timbrado.CFDIS.TFD._11
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     Este código fue generado por una herramienta.
	//     Versión de runtime:4.0.30319.42000
	//
	//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
	//     se vuelve a generar el código.
	// </auto-generated>
	//------------------------------------------------------------------------------
	// 
	// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true,
		Namespace = "http://www.sat.gob.mx/TimbreFiscalDigital")]
	[XmlRoot(Namespace = "http://www.sat.gob.mx/TimbreFiscalDigital",
		IsNullable = false)]
	public partial class TimbreFiscalDigital
	{

		private string versionField;

		private string uUIDField;

		private string fechaTimbradoField;

		private string rfcProvCertifField;

		private string leyendaField;

		private string selloCFDField;

		private string noCertificadoSATField;

		private string selloSATField;

		private string cadenaCertificada;

		public TimbreFiscalDigital()
		{
			this.versionField = "1.1";
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Version
		{
			get { return this.versionField; }
			set { this.versionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string UUID
		{
			get { return this.uUIDField; }
			set { this.uUIDField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string FechaTimbrado
		{
			get { return this.fechaTimbradoField; }
			set { this.fechaTimbradoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string RfcProvCertif
		{
			get { return this.rfcProvCertifField; }
			set { this.rfcProvCertifField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Leyenda
		{
			get { return this.leyendaField; }
			set { this.leyendaField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string SelloCFD
		{
			get { return this.selloCFDField; }
			set { this.selloCFDField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string NoCertificadoSAT
		{
			get { return this.noCertificadoSATField; }
			set { this.noCertificadoSATField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string SelloSAT
		{
			get { return this.selloSATField; }
			set { this.selloSATField = value; }
		}
		public string CadenaCertificada
		{
			get { return this.cadenaCertificada; }
			set { this.cadenaCertificada = value; }
		}
	}
}