using System.Xml.Serialization;

namespace Timbrado.CFDIS.CFDI._40
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     Este código fue generado por una herramienta.
	//     Versión de runtime:4.0.30319.42000
	//
	//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
	//     se vuelve a generar el código.
	// </auto-generated>
	//------------------------------------------------------------------------------
	// 
	// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
	// 



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	[XmlRoot(Namespace = "http://www.sat.gob.mx/cfd/4", IsNullable = false)]
	public partial class Comprobante
	{

		private ComprobanteInformacionGlobal informacionGlobalField;

		private ComprobanteCfdiRelacionados[] cfdiRelacionadosField;

		private ComprobanteEmisor emisorField;

		private ComprobanteReceptor receptorField;

		private ComprobanteConcepto[] conceptosField;

		private ComprobanteImpuestos impuestosField;

		private ComprobanteComplemento complementoField;

		private ComprobanteAddenda addendaField;

		private string versionField;

		private string serieField;

		private string folioField;

		private string fechaField;

		private string selloField;

		private string formaPagoField;

		private bool formaPagoFieldSpecified;

		private string noCertificadoField;

		private string certificadoField;

		private string condicionesDePagoField;

		private string subTotalField;

		private string descuentoField;

		private bool descuentoFieldSpecified;

		private string monedaField;

		private string tipoCambioField;

		private bool tipoCambioFieldSpecified;

		private string totalField;

		private string tipoDeComprobanteField;

		private string exportacionField;

		private string metodoPagoField;

		private bool metodoPagoFieldSpecified;

		private string lugarExpedicionField;

		private string confirmacionField;

		public Comprobante()
		{
			this.versionField = "4.0";
		}

		/// <remarks/>
		public ComprobanteInformacionGlobal InformacionGlobal
		{
			get { return this.informacionGlobalField; }
			set { this.informacionGlobalField = value; }
		}

		/// <remarks/>
		[XmlElement("CfdiRelacionados")]
		public ComprobanteCfdiRelacionados[] CfdiRelacionados
		{
			get { return this.cfdiRelacionadosField; }
			set { this.cfdiRelacionadosField = value; }
		}

		/// <remarks/>
		public ComprobanteEmisor Emisor
		{
			get { return this.emisorField; }
			set { this.emisorField = value; }
		}

		/// <remarks/>
		public ComprobanteReceptor Receptor
		{
			get { return this.receptorField; }
			set { this.receptorField = value; }
		}

		/// <remarks/>
		[XmlArrayItem("Concepto", IsNullable = false)]
		public ComprobanteConcepto[] Conceptos
		{
			get { return this.conceptosField; }
			set { this.conceptosField = value; }
		}

		/// <remarks/>
		public ComprobanteImpuestos Impuestos
		{
			get { return this.impuestosField; }
			set { this.impuestosField = value; }
		}

		/// <remarks/>
		public ComprobanteComplemento Complemento
		{
			get { return this.complementoField; }
			set { this.complementoField = value; }
		}

		/// <remarks/>
		public ComprobanteAddenda Addenda
		{
			get { return this.addendaField; }
			set { this.addendaField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Version
		{
			get { return this.versionField; }
			set { this.versionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Serie
		{
			get { return this.serieField; }
			set { this.serieField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Folio
		{
			get { return this.folioField; }
			set { this.folioField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Fecha
		{
			get { return this.fechaField; }
			set { this.fechaField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Sello
		{
			get { return this.selloField; }
			set { this.selloField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string FormaPago
		{
			get { return this.formaPagoField; }
			set
			{
				formaPagoFieldSpecified = true;
				this.formaPagoField = value;
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool FormaPagoSpecified
		{
			get { return this.formaPagoFieldSpecified; }
			set { this.formaPagoFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string NoCertificado
		{
			get { return this.noCertificadoField; }
			set { this.noCertificadoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Certificado
		{
			get { return this.certificadoField; }
			set { this.certificadoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string CondicionesDePago
		{
			get { return this.condicionesDePagoField; }
			set { this.condicionesDePagoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string SubTotal
		{
			get { return this.subTotalField; }
			set { this.subTotalField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Descuento
		{
			get { return this.descuentoField; }
			set
			{
				descuentoFieldSpecified = true;
				this.descuentoField = value;
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool DescuentoSpecified
		{
			get { return this.descuentoFieldSpecified; }
			set { this.descuentoFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Moneda
		{
			get { return this.monedaField; }
			set { this.monedaField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TipoCambio
		{
			get { return this.tipoCambioField; }
			set { this.tipoCambioField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool TipoCambioSpecified
		{
			get { return this.tipoCambioFieldSpecified; }
			set { this.tipoCambioFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Total
		{
			get { return this.totalField; }
			set { this.totalField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TipoDeComprobante
		{
			get { return this.tipoDeComprobanteField; }
			set { this.tipoDeComprobanteField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Exportacion
		{
			get { return this.exportacionField; }
			set { this.exportacionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string MetodoPago
		{
			get { return this.metodoPagoField; }
			set
			{
				metodoPagoFieldSpecified = true;
				this.metodoPagoField = value;
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool MetodoPagoSpecified
		{
			get { return this.metodoPagoFieldSpecified; }
			set { this.metodoPagoFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string LugarExpedicion
		{
			get { return this.lugarExpedicionField; }
			set { this.lugarExpedicionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Confirmacion
		{
			get { return this.confirmacionField; }
			set { this.confirmacionField = value; }
		}

		[XmlAttribute("schemaLocation", Namespace = System.Xml.Schema.XmlSchema.InstanceNamespace)]
		public string xsiSchemaLocation { get; set; }
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteInformacionGlobal
	{

		private string periodicidadField;

		private string mesesField;

		private short añoField;

		/// <remarks/>
		[XmlAttribute()]
		public string Periodicidad
		{
			get { return this.periodicidadField; }
			set { this.periodicidadField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Meses
		{
			get { return this.mesesField; }
			set { this.mesesField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public short Año
		{
			get { return this.añoField; }
			set { this.añoField = value; }
		}
	}



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteCfdiRelacionados
	{

		private ComprobanteCfdiRelacionadosCfdiRelacionado[] cfdiRelacionadoField;

		private string tipoRelacionField;

		/// <remarks/>
		[XmlElement("CfdiRelacionado")]
		public ComprobanteCfdiRelacionadosCfdiRelacionado[] CfdiRelacionado
		{
			get { return this.cfdiRelacionadoField; }
			set { this.cfdiRelacionadoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TipoRelacion
		{
			get { return this.tipoRelacionField; }
			set { this.tipoRelacionField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteCfdiRelacionadosCfdiRelacionado
	{

		private string uUIDField;

		/// <remarks/>
		[XmlAttribute()]
		public string UUID
		{
			get { return this.uUIDField; }
			set { this.uUIDField = value; }
		}
	}



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteEmisor
	{

		private string rfcField;

		private string nombreField;

		private string regimenFiscalField;

		private string facAtrAdquirenteField;

		/// <remarks/>
		[XmlAttribute()]
		public string Rfc
		{
			get { return this.rfcField; }
			set { this.rfcField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Nombre
		{
			get { return this.nombreField; }
			set { this.nombreField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string RegimenFiscal
		{
			get { return this.regimenFiscalField; }
			set { this.regimenFiscalField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string FacAtrAdquirente
		{
			get { return this.facAtrAdquirenteField; }
			set { this.facAtrAdquirenteField = value; }
		}
	}



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteReceptor
	{

		private string rfcField;

		private string nombreField;

		private string domicilioFiscalReceptorField;

		private string residenciaFiscalField;

		private bool residenciaFiscalFieldSpecified;

		private string numRegIdTribField;

		private string regimenFiscalReceptorField;

		private string usoCFDIField;

		/// <remarks/>
		[XmlAttribute()]
		public string Rfc
		{
			get { return this.rfcField; }
			set { this.rfcField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Nombre
		{
			get { return this.nombreField; }
			set { this.nombreField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string DomicilioFiscalReceptor
		{
			get { return this.domicilioFiscalReceptorField; }
			set { this.domicilioFiscalReceptorField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ResidenciaFiscal
		{
			get { return this.residenciaFiscalField; }
			set { this.residenciaFiscalField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool ResidenciaFiscalSpecified
		{
			get { return this.residenciaFiscalFieldSpecified; }
			set { this.residenciaFiscalFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string NumRegIdTrib
		{
			get { return this.numRegIdTribField; }
			set { this.numRegIdTribField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string RegimenFiscalReceptor
		{
			get { return this.regimenFiscalReceptorField; }
			set { this.regimenFiscalReceptorField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string UsoCFDI
		{
			get { return this.usoCFDIField; }
			set { this.usoCFDIField = value; }
		}
	}



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConcepto
	{

		private ComprobanteConceptoImpuestos impuestosField;

		private ComprobanteConceptoACuentaTerceros aCuentaTercerosField;

		private ComprobanteConceptoInformacionAduanera[] informacionAduaneraField;

		private ComprobanteConceptoCuentaPredial[] cuentaPredialField;

		private ComprobanteConceptoComplementoConcepto complementoConceptoField;

		private ComprobanteConceptoParte[] parteField;

		private string claveProdServField;

		private string noIdentificacionField;

		private string cantidadField;

		private string claveUnidadField;

		private string unidadField;

		private string descripcionField;

		private string valorUnitarioField;

		private string importeField;

		private string descuentoField;

		private bool descuentoFieldSpecified;

		private string objetoImpField;

		/// <remarks/>
		public ComprobanteConceptoImpuestos Impuestos
		{
			get { return this.impuestosField; }
			set { this.impuestosField = value; }
		}

		/// <remarks/>
		public ComprobanteConceptoACuentaTerceros ACuentaTerceros
		{
			get { return this.aCuentaTercerosField; }
			set { this.aCuentaTercerosField = value; }
		}

		/// <remarks/>
		[XmlElement("InformacionAduanera")]
		public ComprobanteConceptoInformacionAduanera[] InformacionAduanera
		{
			get { return this.informacionAduaneraField; }
			set { this.informacionAduaneraField = value; }
		}

		/// <remarks/>
		[XmlElement("CuentaPredial")]
		public ComprobanteConceptoCuentaPredial[] CuentaPredial
		{
			get { return this.cuentaPredialField; }
			set { this.cuentaPredialField = value; }
		}

		/// <remarks/>
		public ComprobanteConceptoComplementoConcepto ComplementoConcepto
		{
			get { return this.complementoConceptoField; }
			set { this.complementoConceptoField = value; }
		}

		/// <remarks/>
		[XmlElement("Parte")]
		public ComprobanteConceptoParte[] Parte
		{
			get { return this.parteField; }
			set { this.parteField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ClaveProdServ
		{
			get { return this.claveProdServField; }
			set { this.claveProdServField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string NoIdentificacion
		{
			get { return this.noIdentificacionField; }
			set { this.noIdentificacionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Cantidad
		{
			get { return this.cantidadField; }
			set { this.cantidadField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ClaveUnidad
		{
			get { return this.claveUnidadField; }
			set { this.claveUnidadField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Unidad
		{
			get { return this.unidadField; }
			set { this.unidadField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Descripcion
		{
			get { return this.descripcionField; }
			set { this.descripcionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ValorUnitario
		{
			get { return this.valorUnitarioField; }
			set { this.valorUnitarioField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Importe
		{
			get { return this.importeField; }
			set { this.importeField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Descuento
		{
			get { return this.descuentoField; }
			set { this.descuentoField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool DescuentoSpecified
		{
			get { return this.descuentoFieldSpecified; }
			set { this.descuentoFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ObjetoImp
		{
			get { return this.objetoImpField; }
			set { this.objetoImpField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoImpuestos
	{

		private ComprobanteConceptoImpuestosTraslado[] trasladosField;

		private ComprobanteConceptoImpuestosRetencion[] retencionesField;

		/// <remarks/>
		[XmlArrayItem("Traslado", IsNullable = false)]
		public ComprobanteConceptoImpuestosTraslado[] Traslados
		{
			get { return this.trasladosField; }
			set { this.trasladosField = value; }
		}

		/// <remarks/>
		[XmlArrayItem("Retencion", IsNullable = false)]
		public ComprobanteConceptoImpuestosRetencion[] Retenciones
		{
			get { return this.retencionesField; }
			set { this.retencionesField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoImpuestosTraslado
	{

		private string baseField;

		private string impuestoField;

		private string tipoFactorField;

		private string tasaOCuotaField;

		private bool tasaOCuotaFieldSpecified;

		private string importeField;

		private bool importeFieldSpecified;

		/// <remarks/>
		[XmlAttribute()]
		public string Base
		{
			get { return this.baseField; }
			set { this.baseField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Impuesto
		{
			get { return this.impuestoField; }
			set { this.impuestoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TipoFactor
		{
			get { return this.tipoFactorField; }
			set { this.tipoFactorField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TasaOCuota
		{
			get { return this.tasaOCuotaField; }
			set {
                tasaOCuotaFieldSpecified = true;
                this.tasaOCuotaField = value;
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool TasaOCuotaSpecified
		{
			get { return this.tasaOCuotaFieldSpecified; }
			set {
				tasaOCuotaFieldSpecified = true;
				this.tasaOCuotaFieldSpecified = value;
			}
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Importe
		{
			get { return this.importeField; }
			set {
                importeFieldSpecified = true;
                this.importeField = value; 
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool ImporteSpecified
		{
			get { return this.importeFieldSpecified; }
			set { this.importeFieldSpecified = value; }
		}
	}



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoImpuestosRetencion
	{

		private string baseField;

		private string impuestoField;

		private string tipoFactorField;

		private string tasaOCuotaField;

		private string importeField;

		/// <remarks/>
		[XmlAttribute()]
		public string Base
		{
			get { return this.baseField; }
			set { this.baseField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Impuesto
		{
			get { return this.impuestoField; }
			set { this.impuestoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TipoFactor
		{
			get { return this.tipoFactorField; }
			set { this.tipoFactorField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TasaOCuota
		{
			get { return this.tasaOCuotaField; }
			set { this.tasaOCuotaField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Importe
		{
			get { return this.importeField; }
			set { this.importeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoACuentaTerceros
	{

		private string rfcACuentaTercerosField;

		private string nombreACuentaTercerosField;

		private string regimenFiscalACuentaTercerosField;

		private string domicilioFiscalACuentaTercerosField;

		/// <remarks/>
		[XmlAttribute()]
		public string RfcACuentaTerceros
		{
			get { return this.rfcACuentaTercerosField; }
			set { this.rfcACuentaTercerosField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string NombreACuentaTerceros
		{
			get { return this.nombreACuentaTercerosField; }
			set { this.nombreACuentaTercerosField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string RegimenFiscalACuentaTerceros
		{
			get { return this.regimenFiscalACuentaTercerosField; }
			set { this.regimenFiscalACuentaTercerosField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string DomicilioFiscalACuentaTerceros
		{
			get { return this.domicilioFiscalACuentaTercerosField; }
			set { this.domicilioFiscalACuentaTercerosField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoInformacionAduanera
	{

		private string numeroPedimentoField;

		/// <remarks/>
		[XmlAttribute()]
		public string NumeroPedimento
		{
			get { return this.numeroPedimentoField; }
			set { this.numeroPedimentoField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoCuentaPredial
	{

		private string numeroField;

		/// <remarks/>
		[XmlAttribute()]
		public string Numero
		{
			get { return this.numeroField; }
			set { this.numeroField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoComplementoConcepto
	{

		private System.Xml.XmlElement[] anyField;

		/// <remarks/>
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any
		{
			get { return this.anyField; }
			set { this.anyField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoParte
	{

		private ComprobanteConceptoParteInformacionAduanera[] informacionAduaneraField;

		private string claveProdServField;

		private string noIdentificacionField;

		private string cantidadField;

		private string unidadField;

		private string descripcionField;

		private string valorUnitarioField;

		private bool valorUnitarioFieldSpecified;

		private string importeField;

		private bool importeFieldSpecified;

		/// <remarks/>
		[XmlElement("InformacionAduanera")]
		public ComprobanteConceptoParteInformacionAduanera[] InformacionAduanera
		{
			get { return this.informacionAduaneraField; }
			set { this.informacionAduaneraField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ClaveProdServ
		{
			get { return this.claveProdServField; }
			set { this.claveProdServField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string NoIdentificacion
		{
			get { return this.noIdentificacionField; }
			set { this.noIdentificacionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Cantidad
		{
			get { return this.cantidadField; }
			set { this.cantidadField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Unidad
		{
			get { return this.unidadField; }
			set { this.unidadField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Descripcion
		{
			get { return this.descripcionField; }
			set { this.descripcionField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string ValorUnitario
		{
			get { return this.valorUnitarioField; }
			set { this.valorUnitarioField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool ValorUnitarioSpecified
		{
			get { return this.valorUnitarioFieldSpecified; }
			set { this.valorUnitarioFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Importe
		{
			get { return this.importeField; }
			set { this.importeField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool ImporteSpecified
		{
			get { return this.importeFieldSpecified; }
			set { this.importeFieldSpecified = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteConceptoParteInformacionAduanera
	{

		private string numeroPedimentoField;

		/// <remarks/>
		[XmlAttribute()]
		public string NumeroPedimento
		{
			get { return this.numeroPedimentoField; }
			set { this.numeroPedimentoField = value; }
		}
	}



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteImpuestos
	{

		private ComprobanteImpuestosRetencion[] retencionesField;

		private ComprobanteImpuestosTraslado[] trasladosField;

		private string totalImpuestosRetenidosField;

		private bool totalImpuestosRetenidosFieldSpecified;

		private string totalImpuestosTrasladadosField;

		private bool totalImpuestosTrasladadosFieldSpecified;

		/// <remarks/>
		[XmlArrayItem("Retencion", IsNullable = false)]
		public ComprobanteImpuestosRetencion[] Retenciones
		{
			get { return this.retencionesField; }
			set { this.retencionesField = value; }
		}

		/// <remarks/>
		[XmlArrayItem("Traslado", IsNullable = false)]
		public ComprobanteImpuestosTraslado[] Traslados
		{
			get { return this.trasladosField; }
			set { this.trasladosField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TotalImpuestosRetenidos
		{
			get { return this.totalImpuestosRetenidosField; }
			set { this.totalImpuestosRetenidosField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool TotalImpuestosRetenidosSpecified
		{
			get { return this.totalImpuestosRetenidosFieldSpecified; }
			set { this.totalImpuestosRetenidosFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TotalImpuestosTrasladados
		{
			get { return this.totalImpuestosTrasladadosField; }
			set {
				totalImpuestosTrasladadosFieldSpecified = true;
                this.totalImpuestosTrasladadosField = value; 
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool TotalImpuestosTrasladadosSpecified
		{
			get { return this.totalImpuestosTrasladadosFieldSpecified; }
			set { this.totalImpuestosTrasladadosFieldSpecified = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteImpuestosRetencion
	{

		private string impuestoField;

		private string importeField;

		/// <remarks/>
		[XmlAttribute()]
		public string Impuesto
		{
			get { return this.impuestoField; }
			set { this.impuestoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Importe
		{
			get { return this.importeField; }
			set { this.importeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteImpuestosTraslado
	{

		private string baseField;

		private string impuestoField;

		private string tipoFactorField;

		private string tasaOCuotaField;

		private bool tasaOCuotaFieldSpecified;

		private string importeField;

		private bool importeFieldSpecified;

		/// <remarks/>
		[XmlAttribute()]
		public string Base
		{
			get { return this.baseField; }
			set { this.baseField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Impuesto
		{
			get { return this.impuestoField; }
			set { this.impuestoField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TipoFactor
		{
			get { return this.tipoFactorField; }
			set { this.tipoFactorField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string TasaOCuota
		{
			get { return this.tasaOCuotaField; }
			set {
				tasaOCuotaFieldSpecified = true;
                this.tasaOCuotaField = value; 
			}
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool TasaOCuotaSpecified
		{
			get { return this.tasaOCuotaFieldSpecified; }
			set { this.tasaOCuotaFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string Importe
		{
			get { return this.importeField; }
			set {
				importeFieldSpecified = true;
				this.importeField = value; }
		}

		/// <remarks/>
		[XmlIgnore()]
		public bool ImporteSpecified
		{
			get { return this.importeFieldSpecified; }
			set { this.importeFieldSpecified = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteComplemento
	{

		private System.Xml.XmlElement[] anyField;

		/// <remarks/>
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any
		{
			get { return this.anyField; }
			set { this.anyField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/4")]
	public partial class ComprobanteAddenda
	{

		private System.Xml.XmlElement[] anyField;

		/// <remarks/>
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any
		{
			get { return this.anyField; }
			set { this.anyField = value; }
		}
	}

}